# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency

url: https://seanhung06.github.io
baseurl: /seanhung06.github.io

title      : Li-Xuan Hong 
email      : lixuanhong06@gmail.com #this is also the email contact forms will go to
description: "Current University of Massachusetts Amherst MS, Computer Science Students. <br> Experienced Software Engineer with a demonstrated history of working in the banking industry and participated in several banking projects with Oracle Database and is familiar with financial infrastructure platforms.<br> Also worked at eCloudvalley Digital Technology as a data engineer focusing on Data Analytics Platform Implementation."
author     : Your Name
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"